/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_michaelapp_demo1_JavaNativeLib */

#ifndef _Included_com_michaelapp_demo1_JavaNativeLib
#define _Included_com_michaelapp_demo1_JavaNativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_michaelapp_demo1_JavaNativeLib
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_michaelapp_demo1_JavaNativeLib_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_michaelapp_demo1_JavaNativeLib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_michaelapp_demo1_JavaNativeLib_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
